version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REACT_APP_ENV=production
      - REACT_APP_API_URL=/api
      - REACT_APP_ASSETS_URL=
    volumes:
      # Persistent volume for data
      - km-data:/app/server/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  km-data:
    # Creates a named volume for persisting data between container restarts 
